"""004_create_estructura_academica

Revision ID: 7c065d851ca7
Revises: 7c7e8567af08
Create Date: 2026-06-18 20:55:42.330859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c065d851ca7'
down_revision: Union[str, Sequence[str], None] = '7c7e8567af08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carrera',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'codigo', name='uq_carrera_tenant_codigo')
    )
    op.create_index(op.f('ix_carrera_tenant_id'), 'carrera', ['tenant_id'], unique=False)
    op.create_table('materia',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'codigo', name='uq_materia_tenant_codigo')
    )
    op.create_index(op.f('ix_materia_tenant_id'), 'materia', ['tenant_id'], unique=False)
    op.create_table('cohorte',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('carrera_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('vig_desde', sa.String(length=10), nullable=False),
    sa.Column('vig_hasta', sa.String(length=10), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['carrera_id'], ['carrera.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'carrera_id', 'nombre', name='uq_cohorte_tenant_carrera_nombre')
    )
    op.create_index(op.f('ix_cohorte_carrera_id'), 'cohorte', ['carrera_id'], unique=False)
    op.create_index(op.f('ix_cohorte_tenant_id'), 'cohorte', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cohorte_tenant_id'), table_name='cohorte')
    op.drop_index(op.f('ix_cohorte_carrera_id'), table_name='cohorte')
    op.drop_table('cohorte')
    op.drop_index(op.f('ix_materia_tenant_id'), table_name='materia')
    op.drop_table('materia')
    op.drop_index(op.f('ix_carrera_tenant_id'), table_name='carrera')
    op.drop_table('carrera')
    # ### end Alembic commands ###
